version: "2.4" # We use v2.x for resource limit support with Docker Compose

services:

  corpbot:
    image: corpnewt/corpbot:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../.env ## Use a .env file at the root
    ## Alternatively you can comment out the
    ## `environment:` object below and use that instead of the .env file#
    # environment:
    #   SETTINGS_DICT_PREFIX: "bot_prefix"
    #   SETTINGS_DICT_TOKEN: "discord_token"
    #   SETTINGS_DICT_WEATHER: "weather_api_key"
    #   SETTINGS_DICT_CURRENCY: "currency_api_key"
    depends_on:
      - lavalink
    networks:
      - corpbot_network
    volumes:
      - corpbot_data:/data
    cpus: 0.5
    mem_limit: 1024m
    mem_reservation: 512m

  lavalink:
    image: 1conan/lavalink:latest
    volumes:
      - ${PWD}/lavalink.yaml:/config/application.yml
    networks:
      - corpbot_network
    cpus: 0.5
    mem_limit: 1024m
    mem_reservation: 512m

networks:
  corpbot:

volumes:
  corpbot_data:
